#!/usr/bin/env python3
"""
Security Report Builder
Aggregates CobraScan JSON results into stylized HTML reports.
Groups all module results by target - one HTML file per target.
"""

from __future__ import annotations

import json
import datetime
import re
from pathlib import Path
from typing import Any, Dict, List, Set

# Always output to reports/ directory
REPORTS_DIR = Path("reports")


def _html_escape(s: Any) -> str:
    if s is None:
        return ""
    if not isinstance(s, str):
        s = str(s)
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _slugify(value: str) -> str:
    # Normalize target: strip protocol and trailing slashes
    value = re.sub(r"^https?://", "", value)
    value = value.rstrip("/")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value).strip("-").lower()
    return slug or "target"


def _normalize_target(entry: Dict[str, Any]) -> str:
    """Extract and normalize target from any entry type."""
    scan_info = entry.get("scan_info") or {}
    raw = (
        scan_info.get("hostname")
        or scan_info.get("url")
        or entry.get("target")
        or entry.get("domain")
        or "unknown"
    )
    # Strip protocol and trailing slashes for grouping
    raw = re.sub(r"^https?://", "", str(raw)).rstrip("/").lower()
    return raw


def _timestamp(entry: Dict[str, Any]) -> datetime.datetime:
    si = entry.get("scan_info") or {}
    ts = si.get("scan_timestamp") or entry.get("timestamp")
    try:
        return (
            datetime.datetime.fromisoformat(ts.replace("Z", ""))
            if isinstance(ts, str)
            else datetime.datetime.min
        )
    except Exception:
        return datetime.datetime.min


def _page_html(title: str, body: str, generated_ts: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_html_escape(title)}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="container">
    <header>
      <h1><span class="logo">🛡️</span> {_html_escape(title)}</h1>
      <div class="muted">Generated: {_html_escape(generated_ts)}</div>
    </header>
    {body}
    <footer>
      <p>Report generated by <strong>CobraScan</strong></p>
      <p class="muted">Security Assessment Report</p>
    </footer>
  </div>
</body>
</html>
"""


def _build_web_section(entry: Dict[str, Any]) -> str:
    """Build detailed Web Analyzer section."""
    si = entry.get("scan_info") or {}
    http = entry.get("http_info") or {}
    perf = entry.get("performance") or {}
    headers = entry.get("security_headers") or {}
    tech = entry.get("technologies") or {}
    ports = entry.get("open_ports") or []
    ip_info = entry.get("ip_info") or {}
    dns = entry.get("dns_info") or {}
    ssl = entry.get("ssl_info") or {}
    content = entry.get("content_analysis") or {}

    # Status badge
    status_code = http.get("status_code", "")

    # Missing headers
    missing = headers.get("vulnerabilities") or []
    missing_html = ""
    if missing:
        items = "".join(
            f'<span class="vuln-item">{_html_escape(m)}</span>' for m in missing
        )
        missing_html = f'<div class="alert alert-warning"><strong>⚠️ Security Header Issues:</strong><div class="vuln-list">{items}</div></div>'

    # Open ports
    ports_html = ""
    if ports:
        items = []
        for p in ports:
            if isinstance(p, dict) and p.get("status") == "open":
                items.append(
                    f'<div class="port-item"><div class="port-num">{p.get("port")}</div><div class="port-service">{_html_escape(p.get("service", ""))}</div></div>'
                )
        if items:
            ports_html = f'<h3 class="section-ports">Open Ports ({len(items)})</h3><div class="port-grid">{"".join(items)}</div>'

    # Technologies
    tech_html = ""
    if tech:
        tech_items = []
        if tech.get("backend"):
            tech_items.append(
                f"<li><strong>Backend:</strong> <code>{_html_escape(tech['backend'])}</code></li>"
            )
        if tech.get("cms"):
            tech_items.append(
                f"<li><strong>CMS:</strong> <code>{_html_escape(tech['cms'])}</code></li>"
            )
        if tech.get("javascript_libraries"):
            libs = ", ".join(tech["javascript_libraries"])
            tech_items.append(
                f"<li><strong>JavaScript:</strong> <code>{_html_escape(libs)}</code></li>"
            )
        if tech.get("css_frameworks"):
            css = ", ".join(tech["css_frameworks"])
            tech_items.append(
                f"<li><strong>CSS:</strong> <code>{_html_escape(css)}</code></li>"
            )
        if tech_items:
            tech_html = f'<h3 class="section-tech">Detected Technologies</h3><ul>{"".join(tech_items)}</ul>'

    # SSL Info
    ssl_html = ""
    if ssl and ssl.get("certificate"):
        cert = ssl["certificate"]
        ssl_status = "✅ Valid" if ssl.get("cert_valid") else "❌ Invalid"
        ssl_html = f"""<h3 class="section-ssl">SSL/TLS Certificate</h3>
        <div class="grid">
          <div class="info-item"><strong>Status</strong><span>{ssl_status}</span></div>
          <div class="info-item"><strong>Issuer</strong><span>{_html_escape(cert.get("issuer", {}).get("organizationName", "N/A"))}</span></div>
          <div class="info-item"><strong>Expires</strong><span>{_html_escape(ssl.get("expiry_date", "N/A"))} ({ssl.get("days_until_expiry", "?")} days)</span></div>
          <div class="info-item"><strong>TLS Version</strong><span>{_html_escape(ssl.get("tls_version", "N/A"))}</span></div>
        </div>"""

    # DNS Info
    dns_html = ""
    if dns:
        a_records = ", ".join(dns.get("a_records", [])) or "None"
        mx_records = ", ".join(dns.get("mx_records", [])) or "None"
        ns_records = ", ".join(dns.get("ns_records", [])) or "None"
        dns_html = f"""<h3 class="section-dns">DNS Records</h3>
        <div class="grid grid-3">
          <div class="info-item"><strong>A Records</strong><span>{_html_escape(a_records)}</span></div>
          <div class="info-item"><strong>MX Records</strong><span>{_html_escape(mx_records)}</span></div>
          <div class="info-item"><strong>NS Records</strong><span>{_html_escape(ns_records)}</span></div>
        </div>"""

    # IP/Geo Info
    geo_html = ""
    if ip_info:
        geo = ip_info.get("geolocation", {})
        geo_html = f"""<h3>IP Information</h3>
        <div class="grid">
          <div class="info-item"><strong>IP Address</strong><span>{_html_escape(ip_info.get("ip_address", "N/A"))}</span></div>
          <div class="info-item"><strong>Reverse DNS</strong><span>{_html_escape(ip_info.get("reverse_dns", "N/A"))}</span></div>
          <div class="info-item"><strong>Location</strong><span>{_html_escape(geo.get("city", ""))}, {_html_escape(geo.get("country", ""))}</span></div>
          <div class="info-item"><strong>ISP</strong><span>{_html_escape(geo.get("isp", "N/A"))}</span></div>
        </div>"""

    # Content Analysis
    content_html = ""
    if content:
        emails = ", ".join(content.get("emails", [])) or "None found"
        phones = ", ".join(content.get("phone_numbers", [])) or "None found"
        content_html = f"""<h3>Content Analysis</h3>
        <div class="grid">
          <div class="info-item"><strong>Page Title</strong><span>{_html_escape(content.get("page_title", "N/A"))}</span></div>
          <div class="info-item"><strong>Word Count</strong><span>{content.get("word_count", 0)}</span></div>
          <div class="info-item"><strong>Emails Found</strong><span>{_html_escape(emails)}</span></div>
          <div class="info-item"><strong>Phone Numbers</strong><span>{_html_escape(phones)}</span></div>
        </div>"""

    open_port_count = len(
        [p for p in ports if isinstance(p, dict) and p.get("status") == "open"]
    )

    return f"""<section class="card">
      <h2><span class="icon">🌐</span> Web Analysis</h2>
      <div class="stats-row">
        <div class="stat-item"><span class="stat-value">{status_code}</span><span class="stat-label">Status</span></div>
        <div class="stat-item"><span class="stat-value">{perf.get("response_time_ms", 0):.0f}ms</span><span class="stat-label">Response</span></div>
        <div class="stat-item"><span class="stat-value">{perf.get("content_size_kb", 0):.1f}KB</span><span class="stat-label">Size</span></div>
        <div class="stat-item"><span class="stat-value">{open_port_count}</span><span class="stat-label">Open Ports</span></div>
      </div>
      <div class="grid">
        <div class="info-item"><strong>Scanned</strong><span>{_html_escape(si.get("scan_timestamp", ""))}</span></div>
        <div class="info-item"><strong>Proxy</strong><span>{_html_escape(si.get("proxy_used") or "DIRECT")}</span></div>
      </div>
      {missing_html}
      {ports_html}
      {ssl_html}
      {dns_html}
      {geo_html}
      {tech_html}
      {content_html}
    </section>"""


def _build_paths_section(entry: Dict[str, Any]) -> str:
    """Build Path Finder section."""
    found = entry.get("found_paths") or []
    count = entry.get("paths_found", 0)
    checked = entry.get("paths_checked", 0)
    timestamp = entry.get("timestamp", "")
    proxies = entry.get("proxies_used") or []

    rows = []
    for f in found[:100]:
        if isinstance(f, dict):
            status = f.get("status_code", "")
            badge_class = (
                "badge-success"
                if status == 200
                else "badge-warning" if status in (301, 302) else "badge-info"
            )
            rows.append(
                f"""<tr>
              <td><code>{_html_escape(f.get("path", ""))}</code></td>
              <td><span class="badge {badge_class}">{status}</span></td>
              <td>{f.get("content_length", 0)}</td>
              <td>{_html_escape(str(f.get("content_type", ""))[:30])}</td>
            </tr>"""
            )

    table = (
        f"""<table>
      <thead><tr><th>Path</th><th>Status</th><th>Size</th><th>Type</th></tr></thead>
      <tbody>{"".join(rows) or "<tr><td colspan='4'>No paths found</td></tr>"}</tbody>
    </table>"""
        if rows
        else "<p>No sensitive paths discovered.</p>"
    )

    return f"""<section class="card">
      <h2><span class="icon">📂</span> Sensitive Path Finder</h2>
      <div class="stats-row">
        <div class="stat-item"><span class="stat-value">{count}</span><span class="stat-label">Found</span></div>
        <div class="stat-item"><span class="stat-value">{checked}</span><span class="stat-label">Checked</span></div>
      </div>
      <div class="grid">
        <div class="info-item"><strong>Scanned</strong><span>{_html_escape(timestamp)}</span></div>
        <div class="info-item"><strong>Proxy</strong><span>{_html_escape(", ".join(proxies) or "DIRECT")}</span></div>
      </div>
      {table}
    </section>"""


def _build_subdomain_section(entry: Dict[str, Any]) -> str:
    """Build Subdomain Enumeration section."""
    found = entry.get("found_subdomains") or entry.get("all_subdomains") or []
    timestamp = entry.get("timestamp", "")
    proxy = entry.get("proxy_used")
    results = entry.get("scan_results") or {}

    items = []
    for sub in found[:100]:
        if isinstance(sub, dict):
            name = sub.get("full_domain") or sub.get("subdomain", "")
            ips = ", ".join(sub.get("ip_addresses", []) or [])
            items.append(
                f'<li><code>{_html_escape(name)}</code>{" - " + _html_escape(ips) if ips else ""}</li>'
            )
        else:
            items.append(f"<li><code>{_html_escape(sub)}</code></li>")

    methods_html = ""
    if results:
        methods_html = f"""<div class="grid grid-3">
          <div class="info-item"><strong>Cert Transparency</strong><span>{results.get("cert_transparency", 0)}</span></div>
          <div class="info-item"><strong>DNS Bruteforce</strong><span>{results.get("dns_bruteforce", 0)}</span></div>
          <div class="info-item"><strong>Zone Transfer</strong><span>{"Vulnerable!" if results.get("zone_transfer_vulnerable") else "Protected"}</span></div>
        </div>"""

    return f"""<section class="card">
      <h2><span class="icon">🔍</span> Subdomain Enumeration</h2>
      <div class="stats-row">
        <div class="stat-item"><span class="stat-value">{len(found)}</span><span class="stat-label">Subdomains</span></div>
      </div>
      <div class="grid">
        <div class="info-item"><strong>Scanned</strong><span>{_html_escape(timestamp)}</span></div>
        <div class="info-item"><strong>Proxy</strong><span>{_html_escape(proxy or "DIRECT")}</span></div>
      </div>
      {methods_html}
      <h3>Discovered Subdomains</h3>
      <ul>{"".join(items) or "<li>No subdomains found</li>"}</ul>
    </section>"""


def _build_vuln_section(entry: Dict[str, Any]) -> str:
    """Build Vulnerability Scanner section."""
    findings = entry.get("findings") or []
    summary = entry.get("summary") or {}
    scans = entry.get("scans") or {}
    timestamp = entry.get("scan_timestamp", "")
    target = entry.get("target", "")

    # Severity counts
    by_sev = summary.get("by_severity", {})
    critical = by_sev.get("CRITICAL", 0)
    high = by_sev.get("HIGH", 0)
    medium = by_sev.get("MEDIUM", 0)
    low = by_sev.get("LOW", 0)
    total = summary.get("total_findings", 0)

    # Risk score color
    risk_class = (
        "critical"
        if critical > 0
        else "high" if high > 0 else "medium" if medium > 0 else "low"
    )

    # Build findings table
    findings_rows = []
    for f in sorted(
        findings,
        key=lambda x: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"].index(
            x.get("severity", "INFO")
        ),
    ):
        sev = f.get("severity", "INFO")
        sev_class = f"badge-{sev.lower()}"
        owasp = f.get("owasp", "")
        cve = f.get("cve", "")

        findings_rows.append(
            f"""<tr class="finding-row finding-{sev.lower()}">
          <td><span class="badge {sev_class}">{sev}</span></td>
          <td>
            <strong>{_html_escape(f.get("title", ""))}</strong>
            <div class="finding-desc">{_html_escape(f.get("description", ""))}</div>
            {f'<div class="finding-evidence"><code>{_html_escape(f.get("evidence", ""))}</code></div>' if f.get("evidence") else ""}
          </td>
          <td>{_html_escape(f.get("category", ""))}</td>
          <td>{_html_escape(owasp)}</td>
          <td>{_html_escape(cve) if cve else "-"}</td>
        </tr>"""
        )

    findings_table = (
        f"""<table class="findings-table">
      <thead><tr><th>Severity</th><th>Finding</th><th>Category</th><th>OWASP</th><th>CVE</th></tr></thead>
      <tbody>{"".join(findings_rows) or "<tr><td colspan='5'>No vulnerabilities detected</td></tr>"}</tbody>
    </table>"""
        if findings
        else "<p class='no-vulns'>✅ No vulnerabilities detected</p>"
    )

    # OWASP categories mapping
    owasp_cats = {
        "A01": "Broken Access Control",
        "A02": "Cryptographic Failures",
        "A03": "Injection",
        "A04": "Insecure Design",
        "A05": "Security Misconfiguration",
        "A06": "Vulnerable Components",
        "A07": "Auth Failures",
        "A08": "Data Integrity Failures",
        "A09": "Logging Failures",
        "A10": "SSRF",
    }

    # Group findings by OWASP
    owasp_grouped = {}
    for f in findings:
        owasp = f.get("owasp", "N/A")
        if owasp not in owasp_grouped:
            owasp_grouped[owasp] = []
        owasp_grouped[owasp].append(f)

    owasp_items = []
    for owasp_id in [
        "A01",
        "A02",
        "A03",
        "A04",
        "A05",
        "A06",
        "A07",
        "A08",
        "A09",
        "A10",
    ]:
        cat_name = owasp_cats.get(owasp_id, "Unknown")
        cat_findings = owasp_grouped.get(owasp_id, [])
        if cat_findings:
            max_sev = min(
                ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"].index(
                    f.get("severity", "INFO")
                )
                for f in cat_findings
            )
            status_class = (
                "vuln-critical"
                if max_sev <= 1
                else "vuln-medium" if max_sev == 2 else "vuln-low"
            )
            status_icon = "⚠️" if max_sev <= 2 else "ℹ️"
        else:
            status_class = "vuln-pass"
            status_icon = "✅"
        owasp_items.append(
            f'<div class="owasp-item {status_class}"><span class="owasp-id">{owasp_id}</span><span class="owasp-name">{cat_name}</span><span class="owasp-status">{status_icon} {len(cat_findings)}</span></div>'
        )

    owasp_grid = f'<div class="owasp-grid">{"".join(owasp_items)}</div>'

    # Scan details
    scan_details = []
    if scans.get("security_headers"):
        sh = scans["security_headers"]
        missing = len(sh.get("missing", []))
        present = len(sh.get("present", []))
        scan_details.append(
            f"<div class='scan-detail'><strong>Security Headers:</strong> {present} present, {missing} missing</div>"
        )
    if scans.get("version_disclosure"):
        vd = scans["version_disclosure"]
        versions = len(vd.get("versions_found", []))
        vulns = len(vd.get("vulnerabilities", []))
        scan_details.append(
            f"<div class='scan-detail'><strong>Version Disclosure:</strong> {versions} detected, {vulns} vulnerable</div>"
        )
    if scans.get("sensitive_files"):
        sf = scans["sensitive_files"]
        exposed = len(sf.get("exposed", []))
        checked = sf.get("files_checked", 0)
        scan_details.append(
            f"<div class='scan-detail'><strong>Sensitive Files:</strong> {exposed} exposed / {checked} checked</div>"
        )

    return f"""<section class="card vuln-card">
      <h2><span class="icon">🔓</span> Vulnerability Assessment</h2>
      <div class="risk-banner {risk_class}">
        <div class="risk-score">{total}</div>
        <div class="risk-label">Total Findings</div>
      </div>
      <div class="stats-row severity-stats">
        <div class="stat-item stat-critical"><span class="stat-value">{critical}</span><span class="stat-label">Critical</span></div>
        <div class="stat-item stat-high"><span class="stat-value">{high}</span><span class="stat-label">High</span></div>
        <div class="stat-item stat-medium"><span class="stat-value">{medium}</span><span class="stat-label">Medium</span></div>
        <div class="stat-item stat-low"><span class="stat-value">{low}</span><span class="stat-label">Low</span></div>
      </div>
      <div class="grid">
        <div class="info-item"><strong>Scanned</strong><span>{_html_escape(timestamp)}</span></div>
        <div class="info-item"><strong>Target</strong><span>{_html_escape(target)}</span></div>
      </div>
      <h3>OWASP Top 10 Assessment</h3>
      {owasp_grid}
      <div class="scan-details">{"".join(scan_details)}</div>
      <h3>Detailed Findings</h3>
      {findings_table}
    </section>"""


def _render_entry(entry: Dict[str, Any]) -> str:
    """Render appropriate section based on entry type."""
    scan_type = entry.get("scan_type", "")

    # Vulnerability Scanner entries
    if scan_type in (
        "full_vuln_scan",
        "quick_vuln_scan",
        "owasp_assessment",
        "injection_scan",
        "ssl_headers_scan",
        "batch_vuln_scan",
    ) or entry.get("findings"):
        return _build_vuln_section(entry)
    # Web Analyzer entries
    elif entry.get("scan_info") and entry.get("http_info"):
        return _build_web_section(entry)
    # Path Finder entries
    elif scan_type in (
        "admin_paths",
        "cms_paths",
        "api_paths",
        "sensitive_paths",
        "all_paths",
        "custom_wordlist",
    ):
        return _build_paths_section(entry)
    # Subdomain entries
    elif scan_type in (
        "cert_transparency",
        "quick_enum",
        "deep_enum",
        "full_enumeration",
        "reverse_dns",
    ) or entry.get("all_subdomains"):
        return _build_subdomain_section(entry)
    else:
        raw = _html_escape(json.dumps(entry, indent=2))
        return f'<section class="card"><h2>Raw Entry</h2><pre>{raw}</pre></section>'


def generate_html_report(results: List[Dict[str, Any]], output_file: str = None) -> str:
    """Generate HTML security reports grouped by target.

    All reports are saved to the reports/ directory.
    One HTML file per unique target (combining all module results).

    Args:
        results: List of saved JSON entries.
        output_file: Ignored - always saves to reports/

    Returns:
        Path to the index file.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    generated_ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Group by normalized target
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for entry in results:
        target = _normalize_target(entry)
        grouped.setdefault(target, []).append(entry)

    # Sort each group by timestamp
    for target in grouped:
        grouped[target] = sorted(grouped[target], key=_timestamp, reverse=True)

    # Generate per-target reports
    target_cards = []
    for target, entries in sorted(grouped.items()):
        slug = _slugify(target)
        target_file = REPORTS_DIR / f"{slug}.html"

        # Count module types
        web_count = sum(1 for e in entries if e.get("scan_info") and e.get("http_info"))
        path_count = sum(
            1
            for e in entries
            if e.get("scan_type")
            in (
                "admin_paths",
                "cms_paths",
                "api_paths",
                "sensitive_paths",
                "all_paths",
                "custom_wordlist",
            )
        )
        sub_count = sum(
            1
            for e in entries
            if e.get("scan_type")
            in (
                "cert_transparency",
                "quick_enum",
                "deep_enum",
                "full_enumeration",
                "reverse_dns",
            )
            or e.get("all_subdomains")
        )
        vuln_count = sum(
            1
            for e in entries
            if e.get("scan_type")
            in (
                "full_vuln_scan",
                "quick_vuln_scan",
                "owasp_assessment",
                "injection_scan",
                "ssl_headers_scan",
                "batch_vuln_scan",
            )
            or e.get("findings")
        )

        # Build sections - dedupe by taking latest of each type
        sections = []
        seen_types: Set[str] = set()

        for entry in entries:
            # Vulnerability scan entries (check first since they have findings)
            entry_type = entry.get("scan_type", "")
            if entry_type in (
                "full_vuln_scan",
                "quick_vuln_scan",
                "owasp_assessment",
                "injection_scan",
                "ssl_headers_scan",
                "batch_vuln_scan",
            ) or entry.get("findings"):
                if "vuln" not in seen_types:
                    sections.append(_render_entry(entry))
                    seen_types.add("vuln")
            elif entry.get("scan_info") and entry.get("http_info"):
                if "web" not in seen_types:
                    sections.append(_render_entry(entry))
                    seen_types.add("web")
            elif entry.get("scan_type"):
                stype = entry.get("scan_type")
                if stype not in seen_types:
                    sections.append(_render_entry(entry))
                    seen_types.add(stype)
            elif entry.get("all_subdomains") and "full_enum" not in seen_types:
                sections.append(_render_entry(entry))
                seen_types.add("full_enum")

        body = f"""
        <div class="card">
          <h2>Target Overview</h2>
          <div class="stats-row">
            <div class="stat-item"><span class="stat-value">{len(entries)}</span><span class="stat-label">Total Scans</span></div>
            <div class="stat-item"><span class="stat-value">{web_count}</span><span class="stat-label">Web Analysis</span></div>
            <div class="stat-item"><span class="stat-value">{path_count}</span><span class="stat-label">Path Scans</span></div>
            <div class="stat-item"><span class="stat-value">{sub_count}</span><span class="stat-label">Subdomain Scans</span></div>
            <div class="stat-item"><span class="stat-value">{vuln_count}</span><span class="stat-label">Vuln Scans</span></div>
          </div>
          <div class="info-item"><strong>Target</strong><span>{_html_escape(target)}</span></div>
        </div>
        {"".join(sections)}
        """

        html = _page_html(f"CobraScan - {target}", body, generated_ts)
        with open(target_file, "w", encoding="utf-8") as f:
            f.write(html)

        target_cards.append(
            f"""
        <div class="card target-card">
          <div class="target-info">
            <h2>{_html_escape(target)}</h2>
            <div class="target-meta">
              <span><span class="pill">{len(entries)}</span> scans</span>
              <span>🌐 {web_count} | 📂 {path_count} | 🔍 {sub_count} | 🔓 {vuln_count}</span>
            </div>
          </div>
          <a href="{slug}.html" class="view-btn">View Report →</a>
        </div>
        """
        )

    # Build index
    index_body = f"""
    <div class="card">
      <h2>Report Summary</h2>
      <div class="stats-row">
        <div class="stat-item"><span class="stat-value">{len(results)}</span><span class="stat-label">Total Entries</span></div>
        <div class="stat-item"><span class="stat-value">{len(grouped)}</span><span class="stat-label">Unique Targets</span></div>
      </div>
    </div>
    <h2 style="margin: 24px 0 16px; font-size: 20px;">📋 Target Reports</h2>
    {"".join(target_cards) or '<div class="card"><p>No targets found.</p></div>'}
    """

    index_file = REPORTS_DIR / "index.html"
    index_html = _page_html("CobraScan Security Reports", index_body, generated_ts)
    with open(index_file, "w", encoding="utf-8") as f:
        f.write(index_html)

    return str(index_file)
